name: 'Build react app for GH Pages'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin gh-pages:refs/remotes/origin/gh-pages
      - run: git checkout --progress --force -B gh-pages refs/remotes/origin/gh-pages
      - run: npm ci
      - run: npm run build --if-present
      - run: git add build -f
      - run: git commit -m "[CI] GH Action build & deploy"
      - run: git push
